baseURL = "/"
relativeURLs = true
locale = 'en-us'
title = 'Yiwei Shi'
theme = 'paper'

[params]
  # Color mode: "light", "dark", or "auto" (follows system)
  color = "gray"

  # Twitter / GitHub / Instagram handles shown in footer
  twitter = "coolworkout"
  github  = "sssyyw"
  linkedin = 'yiweishi'

